language: php

php:
  - '7.1'
  - '7.2'

branches:
  only:
    - master

before_script:
  - cp .env.travis .env

install: composer install

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls